app/models.py
from . import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin



class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)
    def __repr__(self):
        return '<User %r>' % self.username

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length, Regexp, EqualTo
from wtforms import ValidationError
from ..models import User

class NameForm(Form):
    name = StringField()
    submit = SubmitField('Submit')

class LoginForm(Form):
    username = StringField('Username', validators=[DataRequired(), Length(1, 64)])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Keep me logged in')
    submit = SubmitField('Log In')

class RegistrationForm(Form):
    username = StringField('Username', validators=[DataRequired(), Length(1, 64), Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0, 'Usernames must have only letters, numbers, dots or underscores')])
    password = PasswordField('Password', validators=[DataRequired(), EqualTo('password2', message='Passwords must match.')])
    password2 = PasswordField('Confirm password', validators=[DataRequired()])
    submit = SubmitField('Register')

    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already registered.')

class IPscannerForm(Form):
    ip = StringField('IP address: ', validators=[DataRequired(), Length(1,17),Regexp('\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/\d{1,2}', 0, 'Must input right IP CIDR address')])
    submit = SubmitField('Scan')

app/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config



bootstrap = Bootstrap()
moment = Moment()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'main.login'

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from datetime import datetime
from flask import  session
from . import main
from flask_login import login_required
from flask import render_template, redirect, request, url_for, flash
from flask_login import login_user, logout_user
from ..models import User
from .forms import LoginForm,RegistrationForm,IPscannerForm
from .. import db
from flask import jsonify

from libnmap.process import NmapProcess
from libnmap.parser import NmapParser
import xml.etree.ElementTree
import networkx as nx
from networkx.readwrite import json_graph
import json

@main.route('/', methods=['GET', 'POST'])
def index():
    return render_template('index.html')

@main.route('/about')
def about():
    pass

@main.route('/contact')
def contact():
    pass

@main.route('/scan', methods=['GET', 'POST'])
@login_required
def scan():
    form = IPscannerForm()
    if form.validate_on_submit():
        ip = form.ip.data
        ip = str(ip)
        nm1 = NmapProcess(ip, options="-sn")
        nm1.run()
        parsed = NmapParser.parse(nm1.stdout)
        G = nx.Graph()
        nm2 = NmapProcess("www.baidu.com", options="--traceroute")
        nm2.run()
        collection = xml.etree.ElementTree.fromstring(nm2.stdout)
        nodes = collection.getiterator("hop")
        trace_list = []
        pre_node = ''
        for node in nodes:
            trace_list.append(node.attrib["ipaddr"])
            G.add_node(node.attrib["ipaddr"])
            if pre_node != '':
                G.add_edge(node.attrib["ipaddr"], pre_node)
            pre_node = node.attrib["ipaddr"]
        for host in parsed.hosts:
            if host.is_up():
                G.add_node(host.address)
                G.add_edge(host.address,trace_list[0])
        gra_json = json.dumps(G.adj)
        return render_template('result.html',gra_json=gra_json)
    return render_template('scan.html', form=form)

@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is not None and user.verify_password(form.password.data):
            login_user(user, form.remember_me.data)
            return redirect(request.args.get('next') or url_for('main.index'))
        flash('Invalid username or password.')
    return render_template('login.html', form=form)

@main.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('main.index'))

@main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, password=form.password.data)
        db.session.add(user)
        flash('You can now login.')
        return redirect(url_for('main.login'))
    return render_template('register.html', form=form)

app/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="cn">
<html xmlns="http://www.w3.org/1999/xhtml">
{% extends "bootstrap/base.html" %}
<head>
    {% block head %}
        <meta http-equiv="CONTENT-TYPE" content="text/html; charset=UTF-8">
        <meta name="description" content="A complex local network visualization based on Networkx and Nmap">
        <meta name="author" content="Phantom0301">
        <link rel="stylesheet" type="text/css" href="/static/css/tur.css">
        <link rel="stylesheet" type="text/css" href="/static/css/red.css">
        <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css">
        <title>{% block title %}Cynops System{% endblock %}</title>
        {% block css %}
        {% endblock %}
    {% endblock %}
</head>
<body>
{% block navbar %}
<nav class="navbar fixed-top navbar-toggleable-md navbar-inverse navbar-expanded" role="navigation" id="mainNav">
    <div class="container">
        <button type="button" class="navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fa fa-bars"></i>
        </button>
        <a class="navbar-brand page-scroll" href="/">Cynops</a>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link page-sroll" href="{{ url_for('main.about') }}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link page-sroll" href="{{ url_for('main.scan') }}">Scan</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link page-sroll" href="{{ url_for('main.contact') }}">Contact</a>
                </li>
                <li class="nav-item">
                    {% if current_user.is_authenticated %}
                        <a class="nav-link page-sroll" href="{{ url_for('main.logout') }}">Sign Out</a>
                    {% else %}
                        <a class="nav-link page-sroll" href="{{ url_for('main.login') }}">Sign In</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

{% block content %}
{% endblock %}
</body>

app/templates/index.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}

{% block content %}
{% block page_content %}
    <div class="page-header">
    <header class="masthead" style="background-image: url('static/img/header.jpg');">
        <div class="container h-100">
            <div class="row h-100">
                <div class="col-12 my-auto text-center text-white">
                    <img class="masthead-img img-fluid mb-3" src="/static/img/profile.svg" alt="">
                    <div class="masthead-title">Cynops Local Network VI</div>
                    <hr class="colored">

                    <div class="masthead-subtitle"><a href="{{ url_for('main.scan') }}" style="color: white">click here begin scan</a></div>

                </div>
            </div>
        </div>
    </header>
</div>
{% endblock %}
{% endblock %}

app/templates/login.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}

{% block title %}Cynops - Login{% endblock %}

{% block content %}
{% block page_content %}
    <div class="page-header">
        <header class="masthead" style="background-image: url('static/img/header.jpg');">
            <div class="container h-100">
                <div class="text-center h-100">
                    <div class="col-12 my-auto text-center text-white" style="position: relative;top: 50%;transform: translate(0,-50%);">
                        <div class="masthead-title">Login</div>
                        <hr class="colored">
                        <div class="row mt-4">
                            <div class="col-lg-8 offset-lg-2">
                                {{ wtf.quick_form(form) }}
                                <p>
                                    New User?
                                    <a href="{{ url_for('main.register') }}">
                                    Click here to register
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    </div>
{% endblock %}
{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky - Register{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Register</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/result.html
{% extends "base.html" %}
{% block css %}
    <script src="/static/js/d3.js"></script>
    <script src="/static/js/jsnetworkx.js"></script>
{% endblock %}

{% block content %}
{% block page_content %}
    <div class="page-header">
        <header class="masthead" style="background-image: url('static/img/header.jpg');">
            <div class="container h-100">
                <div class="text-center h-100">
                    <div class="col-12 my-auto text-center text-white" style="position: relative;top: 50%;transform: translate(0,-50%);">
                        <div class="masthead-subtitle">Scan Result</div>
                        <hr class="colored">
                        <div class="row mt-4" style="background-color: rgba(255,255,255,0.5);">
                                <div id="canvas" style="height:500px"></div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    </div>
    <script>
    var False=false;
    var gra_json = {{ gra_json|safe }};
    var G = new jsnx.Graph(gra_json);
    var color = d3.scale.category20();
    jsnx.draw(G,{
        element:'#canvas',
        width:1100,
        height:500,
        layoutAttr: {
        charge: -120,
        linkDistance: 40
        },
        weighted:true,
        withLabels: true,
        labelStyle: {fill: 'white'},
        edgeStyle:{
            'stroke-width':6
        },
        nodeAttr: {
        r: 5,
        title: function(d) { return d.label;}
        },
        nodeStyle: {
        fill: function(d) {
            return color(d.data);
        }},
        stickyDrag: true,
        panZoom:{enabled:true}
    });
</script>
{% endblock %}
{% endblock %}

app/templates/scan.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}

{% block title %}Cynops - Scan{% endblock %}


{% block content %}
{% block page_content %}
    <div class="page-header">
        <header class="masthead" style="background-image: url('static/img/header.jpg');">
            <div class="container h-100">
                <div class="text-center h-100">
                    <div class="col-12 my-auto text-center text-white" style="position: relative;top: 50%;transform: translate(0,-50%);">
                        <div class="masthead-subtitle">Scan</div>
                        <hr class="colored">
                        <div class="row mt-4">
                            <div class="col-lg-8 offset-lg-2">
                                {{ wtf.quick_form(form) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    </div>
{% endblock %}
{% endblock %}

app/templates/user.html
{% extends "bootstrap/base.html" %}

{% block title %}Flasky{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Flasky</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% block page_content %}{% endblock %}
</div>
{% endblock %}